#! /bin/sh

#############################################
###               autostart               ###
#############################################
# autorandr -c
wal -R
killall blueman-applet
blueman-applet &
wmname LG3D

killall -q picom
while pgrep -u $UID -x picom >/dev/null; do killall -q picom; done
picom &

$HOME/.fehbg &
$HOME/.config/polybar/launch.sh &

killall solaar
solaar --window hide &
autorandr -c

#############################################
###             pywal colors              ###
#############################################
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"


#############################################
###           bspc settings               ###
#############################################
bspc config border_width         5
bspc config window_gap           8

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 22
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config pointer_modifier mod1
bspc config click_to_focus button1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc monitor DP2-2 -s DP2-1
bspc desktop -f 1

bspc rule -a Google-chrome border=off
bspc rule -a discord border=off
